# Generated by Django 2.2.5 on 2021-02-27 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='device',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Устройство'),
        ),
        migrations.AddField(
            model_name='person',
            name='living',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='person',
            name='passport',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='invalid_passport', message='asdf', regex='ID\\d{7}')], verbose_name='Паспорт ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Фамилия'),
        ),
    ]
