# Generated by Django 2.2.5 on 2021-03-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0002_auto_20210313_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonebookuser',
            name='passport',
        ),
    ]
