# Generated by Django 2.2.5 on 2021-02-27 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0002_auto_20210227_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='living',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='person',
            name='passport',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='invalid_passport', message='Введите корректный ID', regex='ID\\d{7}')], verbose_name='Паспорт ID'),
        ),
    ]
