# Generated by Django 2.2.5 on 2021-03-13 15:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0003_remove_phonebookuser_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebookuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'invalid': 'Введите корректную почту'}, max_length=254, null=True, verbose_name='Эл.почта'),
        ),
        migrations.AlterField(
            model_name='phonebookuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'Введите номер в формате +996ХХХХХХХХХ'}, max_length=128, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='phonebookuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Такой пользователь уже существует.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='Логин'),
        ),
    ]
