# Generated by Django 2.2.5 on 2021-02-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0003_auto_20210227_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='person',
            name='device_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Устройство'),
        ),
        migrations.AddField(
            model_name='person',
            name='device_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Устройство'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_en',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_ru',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Фамилия'),
        ),
    ]
