# Generated by Django 2.2.5 on 2021-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0004_auto_20210313_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebookuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'invalid': 'Введите корректную почту'}, max_length=254, null=True, verbose_name='Почта'),
        ),
    ]
