# Generated by Django 2.2.5 on 2021-03-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0005_auto_20210313_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebookuser',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Пользователь'), (1, 'Руководитель'), (2, 'Администратор')], verbose_name='Статус'),
        ),
    ]
