# Generated by Django 2.2.5 on 2021-02-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0005_auto_20210227_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
