# Generated by Django 2.2.5 on 2021-03-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0007_auto_20210314_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebookuser',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Пользователь'), (1, 'Руководитель'), (2, 'Администратор')], default=0, null=True, verbose_name='Статус'),
        ),
    ]
