# Generated by Django 2.2.5 on 2021-03-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0008_auto_20210314_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebookuser',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стаж работы'),
        ),
    ]
